
## Alacritty Config ##

import = ["/home/vid/.config/alacritty/theme.toml"] # Import my theme.

[colors]
draw_bold_text_with_bright_colors = true

# Fonts
[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[selection]
save_to_clipboard = false

[shell] # The default terminal shell.
program = "/usr/bin/zsh"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding] # Padding on the sides of the window.
x = 5
y = 5

[cursor.style]
shape = "Beam" # Change the cursor shape (Options: Beam, Block, Underline)
