
################
# Helix Config #
################

# Theme
theme = "tokyonight"

# General
[editor]
line-number = "relative" # better line numbers (only in normal and select mode)
cursorline = true # Highlight all lines with a cursor
mouse = false # makes mouse useless
middle-click-paste = false # disables the most annoying feature in existance
bufferline = "multiple" # draws a line of opened buffers at the top (simmilar to tabline)
auto-info = false # disables menu hints by default

# Auto-completion
auto-completion = true # enables or disables auto-completion
idle-timeout = 0 # sets the timeout before showing auto-complete popup in miliseconds
completion-trigger-len = 1 # how many characters need to be typed before enabling auto-complete
completion-replace = true # replaces the whole word when completing

# Bottom bar
[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "read-only-indicator", "diagnostics"]
center = ["file-name"]
right = ["position", "separator", "total-line-numbers"]
separator = "󰇙"

[editor.file-picker]
hidden = false # don't ignore hidden files

[editor.indent-guides]
character = "󰇙" 
render = true # set to "false" to not see these every tab

[editor.lsp]
auto-signature-help = false # Disable automatically popups of signature parameter help
display-messages = true # Show LSP messages in the status line

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Keybinds
[keys.normal]
"M" = ":toggle-option auto-info" # toggles the visibility of the menu hints
"H" = "jump_view_left"  # only when using multiple windows
"J" = "jump_view_down"  # only when using multiple windows
"K" = "jump_view_up"    # only when using multiple windows
"L" = "jump_view_right" # only when using multiple windows
"C-q" = ":buffer-close" # close current buffer and check if its saved
"C-Q" = ":buffer-close!" # close current buffer no matter what
"C-o" = ":buffer-close-others" # close all buffers but current and check if ther are saved
"C-O" = ":buffer-close-others!" # close all buffers but current no matter what
"esc" = ["collapse_selection", "keep_primary_selection"] # makes esc also delete selections like multiple cursors
"C-n" = "file_picker" # Opens a file picker
"C-b" = "buffer_picker" # Opens a buffer picker
"C-v" = ":vnew" # Vertical right split
"C-h" = ":hnew" # Horizontal bottom split
"C-d" = "delete_word_backward"
"S-tab" = "goto_previous_buffer" # switches tabs
"tab" = "goto_next_buffer" # switches tabs

[keys.insert]
"A-x" = "normal_mode" # Enter normal mode
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
