
################
# Helix Config #
################

# Theme
theme = "tokyonight"

# General
[editor]
cursorline = true # Highlight all lines with a cursor
mouse = false # makes mouse useless
middle-click-paste = false # disables the most annoying feature in existance
bufferline = "multiple" # draws a line of opened buffers at the top (simmilar to tabline)

# Auto-completion
auto-completion = true # enables or disables auto-completion
idle-timeout = 0 # sets the timeout before showing auto-complete popup in miliseconds
completion-trigger-len = 1 # how many characters need to be typed before enabling auto-complete
completion-replace = true # replaces the whole word when completing

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "separator", "file-name"]
center = ["spinner"]
right = ["diagnostics", "selections", "position", "file-encoding"]
separator = "󰇙"

[editor.file-picker]
hidden = false # don't ignore hidden files

[editor.indent-guides]
character = "󰇙"
render = true

[editor.lsp]
auto-signature-help = false # Disable automatically popups of signature parameter help
display-messages = true # Show LSP messages in the status line

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Keybinds
[keys.normal]
"C-n" = "file_picker" # Opens a file picker
"C-b" = "buffer_picker" # Opens a buffer picker
"C-v" = "vsplit" # Vertical right split
"C-h" = "hsplit" # Horizontal bottom split
"C-q" = "wclose" # Close current window
"C-o" = "wonly" # Only keep the current window, closing all the others
"S-tab" = "goto_previous_buffer"
"tab" = "goto_next_buffer"
[keys.insert]
"A-x" = "normal_mode" # Enter normal mode
