[[language]]
name = "cpp"
file-types = ["cc", "cpp", "c++", "cxx"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
file-types = ["c"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
file-types = ["py"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "bash"
file-types = ["sh", "bash", ".zshrc", "conf"]
shebangs = ["sh", "bash"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
